# Generated by Django 3.2.7 on 2021-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('coach', 'coach'), ('student', 'student')], max_length=20),
        ),
    ]
