# Generated by Django 3.2.7 on 2021-09-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='paid',
            new_name='subscribe',
        ),
    ]
