# Generated by Django 3.2.7 on 2021-10-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
