# Generated by Django 3.2.7 on 2021-10-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
