# Generated by Django 3.2.7 on 2021-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211028_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='time_begin_work',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_finish_work',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_visit_gim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
