# Generated by Django 3.2.7 on 2021-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211029_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fathername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
