# Generated by Django 3.2.7 on 2021-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_favouritemusic_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='music.Music'),
        ),
    ]
