# Generated by Django 3.2.7 on 2021-09-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210925_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('playlistItem', models.ManyToManyField(blank=True, null=True, to='music.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.playlistitem'),
            preserve_default=False,
        ),
    ]
