# Generated by Django 3.2.7 on 2021-09-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_playlist_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='playlistItem',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_item',
            field=models.ManyToManyField(blank=True, null=True, to='music.PlaylistItem'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='music.playlist'),
            preserve_default=False,
        ),
    ]
