# Generated by Django 3.2.7 on 2021-09-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210926_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_item',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.playlistitem'),
        ),
    ]
