# Generated by Django 3.2.7 on 2021-09-26 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_auto_20210926_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.music'),
            preserve_default=False,
        ),
    ]
