# Generated by Django 3.2.7 on 2021-09-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210926_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_item',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_item',
            field=models.ManyToManyField(blank=True, null=True, to='music.PlaylistItem'),
        ),
    ]
