# Generated by Django 3.2.7 on 2021-09-26 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20210926_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='music',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.playlist'),
        ),
    ]
