# Generated by Django 3.2.7 on 2021-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20210926_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_item',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='music',
        ),
        migrations.AddField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(to='music.Music'),
        ),
    ]
