# Generated by Django 3.2.7 on 2021-09-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210926_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
    ]
