# Generated by Django 3.2.7 on 2021-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_delete_playlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='music.Music'),
        ),
    ]
