# Generated by Django 3.2.7 on 2021-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_playlist_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemusic',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='music.Music'),
        ),
    ]
