# Generated by Django 3.2.7 on 2021-10-20 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20211009_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='type',
            field=models.CharField(choices=[('Поп', 'Поп'), ('Шансон', 'Шансон'), ('Рок', 'Рок'), ('Хард рок', 'Хард рок'), ('Рэп', 'Рэп'), ('Рок-н-Ролл', 'Рок-н-Ролл'), ('Метал', 'Метал')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
