# Generated by Django 3.2.7 on 2021-10-20 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20211020_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1950)]),
        ),
    ]
