# Generated by Django 3.2.7 on 2021-10-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_music_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.type'),
        ),
    ]
