# Generated by Django 3.2.7 on 2021-10-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20211020_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.type'),
        ),
    ]
