# Generated by Django 3.2.7 on 2021-09-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210919_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.comment'),
        ),
        migrations.AlterField(
            model_name='new',
            name='like',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.like'),
        ),
    ]
