# Generated by Django 3.2.7 on 2021-09-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210923_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.comment'),
        ),
        migrations.AlterField(
            model_name='new',
            name='like',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.like'),
        ),
    ]
