# Generated by Django 3.2.7 on 2021-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210923_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='like',
        ),
        migrations.AddField(
            model_name='new',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='news.Like'),
        ),
    ]
