# Generated by Django 3.2.7 on 2021-09-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210923_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.new'),
        ),
    ]
