# Generated by Django 3.2.7 on 2021-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210923_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_new_comment',
            field=models.ManyToManyField(blank=True, default='0', null=True, related_name='like_new_comment', to='news.Like_new_comment'),
        ),
    ]
