# Generated by Django 3.2.7 on 2021-09-23 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_alter_comment_like_new_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='news.new'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='new',
            name='comment',
        ),
        migrations.AddField(
            model_name='new',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='news.Comment'),
        ),
    ]
