# Generated by Django 3.2.7 on 2021-09-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.comment'),
        ),
    ]
