# Generated by Django 3.2.7 on 2021-09-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_new_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='comment',
        ),
        migrations.AddField(
            model_name='new',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='news.Comment'),
        ),
    ]
