# Generated by Django 3.2.7 on 2021-09-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210930_0847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table='new',
        ),
    ]
