# Generated by Django 3.2.7 on 2021-09-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_new_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='comment',
        ),
    ]
