# Generated by Django 3.2.7 on 2021-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_new_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new',
        ),
        migrations.AddField(
            model_name='new',
            name='Comment',
            field=models.ManyToManyField(blank=True, limit_choices_to=1, null=True, to='news.Comment'),
        ),
    ]
