# Generated by Django 3.2.7 on 2021-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20211009_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='Comment',
            field=models.ManyToManyField(blank=True, null=True, to='news.Comment'),
        ),
    ]
