# Generated by Django 3.2.7 on 2021-10-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20211009_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='new',
        ),
    ]
