# Generated by Django 3.2.7 on 2021-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_rename_comment_comment_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_new_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='like_new_comment',
            field=models.IntegerField(default='0'),
        ),
        migrations.RemoveField(
            model_name='new',
            name='like',
        ),
        migrations.AddField(
            model_name='new',
            name='like',
            field=models.IntegerField(default='0'),
        ),
    ]
