# Generated by Django 3.2.7 on 2021-10-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20211001_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='like',
        ),
        migrations.CreateModel(
            name='LikeNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
            ],
        ),
    ]
