# Generated by Django 3.2.7 on 2021-10-10 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0024_alter_likenew_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likenew',
            name='new',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.new'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likenew',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
