# Generated by Django 3.2.7 on 2021-10-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20211011_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='new',
            new_name='comment',
        ),
    ]
