# Generated by Django 3.2.7 on 2021-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_rename_new_likecomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
