# Generated by Django 3.2.7 on 2021-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
