# Generated by Django 3.2.7 on 2021-09-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltickets',
            options={'verbose_name': 'Все билеты', 'verbose_name_plural': 'Все билеты'},
        ),
        migrations.AlterModelOptions(
            name='userticket',
            options={'verbose_name': 'Билет пользователя', 'verbose_name_plural': 'Билеты пользователя'},
        ),
        migrations.AlterField(
            model_name='alltickets',
            name='finish_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='buy_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
