# Generated by Django 3.2.7 on 2021-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0002_auto_20210919_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltickets',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='buy_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
