# Generated by Django 3.2.7 on 2021-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0004_auto_20210919_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltickets',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='alltickets',
            name='finish_time',
            field=models.DateField(choices=[(1, 1), (7, 7), (30, 30), (365, 365)], verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='alltickets',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='alltickets',
            name='withCoach',
            field=models.BooleanField(verbose_name='С тренером ли?'),
        ),
    ]
