# Generated by Django 3.2.7 on 2021-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0005_auto_20210919_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltickets',
            name='finish_time',
            field=models.IntegerField(choices=[(1, 1), (7, 7), (30, 30), (365, 365)], verbose_name='Период'),
        ),
    ]
