# Generated by Django 3.2.7 on 2021-10-01 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gim', '0008_alter_userticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtraining',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programtraining',
            name='user_to',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('isNew', models.BooleanField(default=True)),
                ('programItems', models.ManyToManyField(to='gim.ProgramTraining')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userT', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
