# Generated by Django 3.2.7 on 2021-10-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gim', '0009_auto_20211001_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTrainingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='programtraining',
            name='number',
        ),
        migrations.RemoveField(
            model_name='programtraining',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='programtraining',
            name='sets',
        ),
        migrations.AddField(
            model_name='programtraining',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtraining',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtraining',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userT', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtraining',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programtraining',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programtraining',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AddField(
            model_name='programtraining',
            name='programItems',
            field=models.ManyToManyField(to='gim.ProgramTrainingItem'),
        ),
    ]
