# Generated by Django 3.2.7 on 2021-10-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0010_auto_20211001_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtraining',
            name='image',
        ),
    ]
