# Generated by Django 3.2.7 on 2021-10-01 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0012_auto_20211001_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtraining',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programtraining',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
