# Generated by Django 3.2.7 on 2021-10-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0013_auto_20211001_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtraining',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programtraining',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
