# Generated by Django 3.2.7 on 2021-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0015_remove_programtraining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtraining',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='programtraining',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
