# Generated by Django 3.2.7 on 2021-10-02 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gim', '0017_alter_programtraining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('programItems', models.ManyToManyField(to='gim.ProgramTrainingItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userD', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
