# Generated by Django 3.2.7 on 2021-10-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0018_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
