# Generated by Django 3.2.7 on 2021-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0019_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='finish_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
