# Generated by Django 3.2.7 on 2021-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0020_userticket_finish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTrainingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='programfood',
            name='number',
        ),
        migrations.AddField(
            model_name='programfood',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programfood',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='programfood',
            name='foodItems',
            field=models.ManyToManyField(to='gim.FoodTrainingItem'),
        ),
    ]
