# Generated by Django 3.2.7 on 2021-10-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0021_auto_20211008_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfood',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
