# Generated by Django 3.2.7 on 2021-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0022_alter_programfood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
