# Generated by Django 3.2.7 on 2021-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0025_programfood_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtraining',
            name='beginAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programtraining',
            name='finishAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
