# Generated by Django 3.2.7 on 2021-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0027_programtrainingitem_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfood',
            name='isNew',
        ),
        migrations.AddField(
            model_name='programfood',
            name='new_type',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
