# Generated by Django 3.2.7 on 2021-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0028_auto_20211010_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfood',
            name='new_type',
        ),
        migrations.RemoveField(
            model_name='programtraining',
            name='isNew',
        ),
        migrations.AddField(
            model_name='programfood',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtraining',
            name='new_type',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
