# Generated by Django 3.2.7 on 2021-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0029_auto_20211010_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='buy_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
