# Generated by Django 3.2.7 on 2021-10-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0030_alter_userticket_buy_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfood',
            name='foodItems',
        ),
        migrations.RemoveField(
            model_name='programfood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programfood',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='DraftFood',
        ),
        migrations.DeleteModel(
            name='FoodTrainingItem',
        ),
        migrations.DeleteModel(
            name='ProgramFood',
        ),
    ]
