# Generated by Django 3.2.7 on 2021-10-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.IntegerField(),
        ),
    ]
