# Generated by Django 3.2.7 on 2021-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20211005_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('eat', 'eat'), ('drink', 'drink')], default='eat', max_length=10),
        ),
    ]
