# Generated by Django 3.2.7 on 2021-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('eat', 'eat'), ('drink', 'drink')], max_length=10),
        ),
    ]
