# Generated by Django 3.2.7 on 2021-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pryce',
            field=models.IntegerField(default=12),
        ),
    ]
